stages:
  - deploy

.base:
  tags:
    - smartive

deploy docker images:
  extends: .base
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_FILE: ./Dockerfile
    DOCKER_TAG: $CI_REGISTRY_IMAGE:latest
    DOCKER_CONTEXT: '.'
    DOCKER_BUILDKIT: '1'
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:18.09-dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - export TAG=$(date -u +"%FT%H-%M-%SUTC")
    - docker build -t smartive/semantic-release-image:latest .
    - docker tag smartive/semantic-release-image:latest smartive/semantic-release-image:$TAG
    - docker push smartive/semantic-release-image:latest
    - docker push smartive/semantic-release-image:$TAG
  only:
    - master
