stages:
  - deploy

.base:
  tags:
    - smartive

deploy docker images:
  extends: .base
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_BUILDKIT: '1'
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build -t smartive/semantic-release-image:latest .
    - docker push smartive/semantic-release-image:latest
  only:
    - master
